// Generated by gencpp from file server_clien/AddInts.msg
// DO NOT EDIT!


#ifndef SERVER_CLIEN_MESSAGE_ADDINTS_H
#define SERVER_CLIEN_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <server_clien/AddIntsRequest.h>
#include <server_clien/AddIntsResponse.h>


namespace server_clien
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace server_clien


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_clien::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::server_clien::AddInts&) { return value(); }
};

template<>
struct DataType< ::server_clien::AddInts > {
  static const char* value()
  {
    return "server_clien/AddInts";
  }

  static const char* value(const ::server_clien::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::server_clien::AddIntsRequest> should match
// service_traits::MD5Sum< ::server_clien::AddInts >
template<>
struct MD5Sum< ::server_clien::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_clien::AddInts >::value();
  }
  static const char* value(const ::server_clien::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_clien::AddIntsRequest> should match
// service_traits::DataType< ::server_clien::AddInts >
template<>
struct DataType< ::server_clien::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::server_clien::AddInts >::value();
  }
  static const char* value(const ::server_clien::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_clien::AddIntsResponse> should match
// service_traits::MD5Sum< ::server_clien::AddInts >
template<>
struct MD5Sum< ::server_clien::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_clien::AddInts >::value();
  }
  static const char* value(const ::server_clien::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_clien::AddIntsResponse> should match
// service_traits::DataType< ::server_clien::AddInts >
template<>
struct DataType< ::server_clien::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::server_clien::AddInts >::value();
  }
  static const char* value(const ::server_clien::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_CLIEN_MESSAGE_ADDINTS_H
